### ISSUE TITLE
Implement standard mouse behavior for selection

### ISSUE THREAD

**Issue by waxlamp** [Kitware/clique#22]
For example:
- [x] hold down Ctrl/Shift while clicking to add a node to the selection?
- [x] clicking on a node should move the focus to that node?
- [x] clicking on the background should clear the selection?
- [x] brushing action to select many nodes at once?

Also we need to have selection-wide action buttons for:
- [x] Deleting nodes
- [x] Expanding nodes

We may also want a button that computes and instantiates the selection of, e.g., the neighbors of the focused node.

**Comment by jeffbaumes** [comment]
I think clicking on a node should clear the prior selection and select only that node. Shift-click to explicitly add to the selection. This may be what you are getting at but I'm not sure.

+1 on selection-wide delete/expand

**Comment by waxlamp** [comment]
Yeah this is pretty much what I meant, but I wasn't sure of the exact setup to use.  I like click-to-clear and shift-click-to-add.

**Comment by waxlamp** [comment]
PR #30 adds the "selection-wide" operation buttons.
